import{a as L,S as w,i as l}from"./assets/vendor-CFFvTae-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();async function g(t,o=1){return(await L.get("https://pixabay.com/api/",{params:{key:"56484901-001e7e85bfee9cf80da113fbf",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),s=document.querySelector(".load-more-btn"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function P({webformatURL:t,largeImageURL:o,tags:r,likes:n,views:e,comments:a,downloads:i}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${o}">
        <img class="gallery-image" src="${t}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${n}</span></p>
        <p class="info-item"><b>Views</b><span>${e}</span></p>
        <p class="info-item"><b>Comments</b><span>${a}</span></p>
        <p class="info-item"><b>Downloads</b><span>${i}</span></p>
      </div>
    </li>
  `}function y(t){if(!d)return;const o=t.map(P).join("");d.insertAdjacentHTML("beforeend",o),S.refresh()}function q(){d&&(d.innerHTML="")}function h(){p&&(p.style.display="block")}function f(){p&&(p.style.display="none")}function v(){s&&(s.classList.remove("is-hidden"),s.style.display="block")}function m(){s&&(s.classList.add("is-hidden"),s.style.display="none")}const M=document.querySelector(".form"),E=document.querySelector(".load-more-btn");let u="",c=1;const $=15;M.addEventListener("submit",B);E.addEventListener("click",H);async function B(t){t.preventDefault();const o=t.currentTarget;if(u=o.elements["search-text"].value.trim(),u===""){l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}c=1,q(),m(),h();try{const r=await g(u,c),n=r.hits,e=r.totalHits;if(n.length===0){f(),l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3});return}y(n),o.reset(),b(e,!1)}catch{l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{f()}}async function H(){c+=1,m(),h();try{const t=await g(u,c),o=t.hits,r=t.totalHits;y(o),x(),b(r,!0)}catch{l.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{f()}}function b(t,o){const r=Math.ceil(t/$);c>=r?(m(),o&&l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}function x(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height,r=document.querySelector(".gallery"),n=window.getComputedStyle(r),e=parseFloat(n.rowGap)||0;window.scrollBy({top:(o+e)*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
